package com.ez.core.exception;

/**
 * Created by Ez on 2017/12/6.
 */
public interface EzCode {

    String RIGHT_BASE = "01";
    String ERROR_BASE = "02";

    String ERROR_SERVER = "01";

    String ERROR_CONFIG = "02";

    String ERROR_BUSI = "03";

    String ERROR_LOGON = "04";

    String ERROR_FILE = "05";


    String ERROR_SERVER_UNCATCH = ERROR_BASE  + ERROR_SERVER + "000";
    String ERROR_SERVER_BOOT = ERROR_BASE  + ERROR_SERVER + "001";
    String ERROR_SERVER_IO = ERROR_BASE  + ERROR_SERVER + "002";
    String ERROR_SERVER_PARAM= ERROR_BASE  + ERROR_SERVER + "003";
    String ERROR_SERVER_NOBEAN = ERROR_BASE  + ERROR_SERVER + "004";
    String ERROR_SERVER_NOACTION = ERROR_BASE  + ERROR_SERVER + "005";
    String ERROR_SERVER_BEANDEFINE = ERROR_BASE  + ERROR_SERVER + "006";

    String ERROR_CONFIG_NOTFOUND = ERROR_BASE  + ERROR_CONFIG + "001";
    String ERROR_CONFIG_FILELOAD = ERROR_BASE  + ERROR_CONFIG + "002";

    String ERROR_BUSI_PARAMS = ERROR_BASE  + ERROR_BUSI + "001";

    String ERROR_LOGON_PARAMS = ERROR_BASE  + ERROR_LOGON + "001";
    String ERROR_LOGON_NOTFOUND = ERROR_BASE  + ERROR_LOGON + "002";
    String ERROR_LOGON_PWD = ERROR_BASE  + ERROR_LOGON + "003";
    String ERROR_LOGON_NOROLE = ERROR_BASE  + ERROR_LOGON + "004";
    String ERROR_LOGON_NOTLOGON = ERROR_BASE  + ERROR_LOGON + "005";


    String ERROR_FILE_UPLOAD = ERROR_BASE  + ERROR_FILE + "001";

}
